# Generated by Django 3.1.7 on 2021-02-23 05:21

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('data', jsonfield.fields.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'index_together': {('category', 'name')},
            },
        ),
    ]
