# Generated by Django 3.1.7 on 2021-02-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='events',
            unique_together={('category', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='events',
            index_together=set(),
        ),
    ]
